CREATE TABLE traffic_tickets (
    id SERIAL PRIMARY KEY,
    detected_speed DOUBLE PRECISION NOT NULL,
    legal_speed DOUBLE PRECISION NOT NULL,
    violation_location VARCHAR(255) NOT NULL,
    violation_date VARCHAR(50) NOT NULL,
    violation_time VARCHAR(50) NOT NULL,
    violation_type VARCHAR(100) NOT NULL,
    license_plate_number VARCHAR(20) NOT NULL,
    vehicle_production_id VARCHAR(50) NOT NULL,
    vehicle_factory VARCHAR(100) NOT NULL,
    vehicle_model VARCHAR(100) NOT NULL,
    vehicle_color VARCHAR(50) NOT NULL,
    vehicle_brand VARCHAR(100) NOT NULL,
    officer_name VARCHAR(100) NOT NULL,
    officer_id VARCHAR(50) NOT NULL,
    officer_rank VARCHAR(50) NOT NULL,
    suspect_name VARCHAR(100) NOT NULL,
    suspect_id VARCHAR(50) NOT NULL,
    suspect_age INTEGER NOT NULL,
    officer_age INTEGER NOT NULL,
    suspect_job VARCHAR(100) NOT NULL,
    suspect_address TEXT NOT NULL,
    suspect_birth_place VARCHAR(100) NOT NULL,
    officer_branch_office_address TEXT NOT NULL
);

