CREATE TABLE Laut (
    id INT AUTO_INCREMENT PRIMARY KEY,
    port_name VARCHAR(100) NOT NULL,
    port_code VARCHAR(20) NOT NULL,
    port_address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    province VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    operator_name VARCHAR(100) NOT NULL,
    operator_contact VARCHAR(100) NOT NULL,
    harbor_master_name VARCHAR(100) NOT NULL,
    harbor_master_id VARCHAR(50) NOT NULL,
    harbor_master_rank VARCHAR(50) NOT NULL,
    harbor_master_office_address TEXT NOT NULL,
    number_of_piers INT NOT NULL,
    main_pier_length DOUBLE NOT NULL,
    max_ship_draft DOUBLE NOT NULL,
    max_ship_length DOUBLE NOT NULL,
    terminal_capacity_passenger INT NOT NULL,
    terminal_capacity_cargo INT NOT NULL,
    operational_hours VARCHAR(100) NOT NULL,
    emergency_contact VARCHAR(100) NOT NULL,
    security_office_name VARCHAR(100) NOT NULL,
    security_officer_id VARCHAR(50) NOT NULL,
    security_level VARCHAR(50) NOT NULL,
    checkin_counter_count INT NOT NULL,
    special_facilities TEXT NOT NULL
);

